import type { NextPage } from "next";
import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import { A11y, Navigation, Autoplay } from "swiper";
import { FaPlus, FaStar, FaCheckDouble, FaUsers } from "react-icons/fa";
import { useEffect, useState } from "react";
import Nav from "../components/Navigation";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const [pageYOffset, setPageYOffset] = useState(0);

  useEventListener(undefined, "scroll", () => {
    setPageYOffset(window.pageYOffset);
  });

  if (pageYOffset > 0 && typeof document !== "undefined") {
    const nav = document.querySelector("nav");
    nav?.classList.add("scrolled");
    nav?.classList.remove("not-scrolled");
  }
  if (pageYOffset === 0 && typeof document !== "undefined") {
    const nav = document.querySelector("nav");
    nav?.classList.remove("scrolled");
    nav?.classList.add("not-scrolled");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Projeto social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <header>
        <img src="/images/logos/IMG-logo-transparente1.png" alt="" />
        <h1>
          CONFIGURANDO DESTINOS
          <br />
          Muay Thai transformando vidas
        </h1>
        <p>
          Aulas gratuitas para crianças em vulnerabilidade social e mulheres que
          sofreram violência domestica.
        </p>
        <button>Saiba mais</button>

        <div className={styles.shapeDivider}>
          <svg
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
          >
            <path
              d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z"
              className={styles.shapeFill}
            ></path>
          </svg>
        </div>
      </header>

      <section className={styles.logos}>
        <div className="box">
          <Swiper
            className="swiperImgs"
            modules={[A11y, Autoplay]}
            spaceBetween={0}
            slidesPerView={6}
            autoplay={{
              delay: 5000,
            }}
            loop={true}
            speed={2800}
            onSwiper={(swiper) => console.log(swiper)}
            onSlideChange={() => console.log("slide change")}
          >
            <SwiperSlide>
              <img src="/images/logos/nicolas-max-developer.png" alt="" />
            </SwiperSlide>

            <SwiperSlide>
              <img src="/images/logos/IMG-logo-transparente1.png" alt="" />
            </SwiperSlide>

            <SwiperSlide>
              <img src="/images/logos/logo-jonatas.svg" alt="" />
            </SwiperSlide>

            {/* <SwiperSlide>
              <img src="/images/logos/empresa-aqui.png" alt="" />
            </SwiperSlide> */}

            {/* <SwiperSlide>
              <img src="/images/logos/empresa-aqui.png" alt="" />
            </SwiperSlide> */}

            {/* <SwiperSlide>
              <img src="/images/logos/" alt="" />
            </SwiperSlide> */}
          </Swiper>
        </div>
      </section>

      <section className={styles.about}>
        <div className={`box ${styles.aboutGrid}`}>
          <div className={styles.aboutUs}>
            <div className={styles.icon}>
              <FaUsers />
            </div>
            <span>SOBRE NÓS</span>
            <h2>Quem nos somos?</h2>
            <p>
              O Centro de Treinamento Muay Thai Girls é um espaço voltado
              exclusivamente para o público feminino e infantil. Nosso maior
              objetivo é trazer mudança na vida de nossas alunas, trazer
              alegria, alto estima e qualidade de vida.
            </p>
          </div>

          <img src="/images/mocao-honrosa.png" alt="" />

          <div className={styles.aboutProject}>
            <p>
              O projeto Configurando Destinos tem como principal objetivo
              transformar a vida de nosso alunos sociais, direcionando-os por
              meio do esporte para uma vida mais saudável com crescimento
              profissional como atletas de Muay Thai. Atualmente contamos com
              dois projetos sociais:
            </p>

            <li>
              Aulas gratis de Muay Thai para crianças com fragilidade social.
            </li>
            <li>
              Aulas gratis de Muay Thai para mulheres que sofreram violência
              domestica.
            </li>
          </div>
        </div>
      </section>

      <section>
        <div className={`box ${styles.partners}`}>
          <h2>Empresas que estão conosco</h2>
          <p>
            Todo o trabalho desenvolvido pelo projeto Configurando Destinos, conta com a
            colaboração de um corpo de voluntariádos formado por profissionais e
            empresas de diversas áreas.
          </p>

          <div className={styles.cards}>
            <div className={`${styles.card} ${styles.CTMuayThai}`}>
              <img src="/images/logos/IMG-logo-transparente.png" />
              <h4>C.T Muay Thai Girls</h4>
              <p>
                Um Centro de Treinamento exclusivamente para mulheres.
              </p>
            </div>

            <div className={styles.card}>
              <img src="/images/logos/spotify.svg" />
              <h4>Google Services</h4>
              <p>
                The phrasal sequence of the is now so that many campaign and
                benefit
              </p>
            </div>

            <div className={styles.card}>
              <img src="/images/logos/amazon.svg" />
              <h4>Google Services</h4>
              <p>
                The phrasal sequence of the is now so that many campaign and
                benefit
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.disclaimer}>
        <div className={`box ${styles.disclaimerBox}`}>
          <h2>CONFIGURANDO DESTINOS</h2>
          <p>
            Soliedariedade não é dar o que sobra, é dar o que falta. Faça parte
            dessa luta que está mudando a vida de inumeras pessoas!!
          </p>
          <div className={styles.icon}>♠</div>
        </div>
      </section>

      <section className={styles.projectSection}>
        <div className="box">
          <h2>Nossos projetos</h2>
          <p>
            Atualmente contamos com dois projetos sociais, Muay Thai para
            crianças com fragilidade social e Muay Thai para mulheres que
            sofreram violência domestica.
          </p>

          <div className={styles.projects}>
            <div className={styles.project}>
              <div style={{ backgroundColor: "#F2FAF7" }}>
                <img src="/images/kids.png" alt="" />
              </div>
              <h3>Muay Thai Infantil</h3>
              <p>Thaty Azevedo</p>
            </div>

            <div className={styles.project}>
              <div style={{ backgroundColor: "#F6F6FE" }}>
                <img src="/images/womans.png" alt="" />
              </div>
              <h3>Muay Thai Feminino</h3>
              <p>Thaty Azevedo</p>
            </div>
          </div>
        </div>
      </section>

      <section>
        <div className={`box ${styles.donation}`}>
          <div className={`${styles.donationBox} ${styles.first}`}>
            <span>
              Benefícios III
              <FaStar className={styles.star} />
              <FaStar className={styles.star} />
              <FaStar className={styles.star} />
            </span>
            <strong>R$ 1.500,00 +</strong>

            <p>
              <FaCheckDouble className={styles.checked} /> Site profissional
              completo
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> Pacote com 3 vídeos
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> Pacote com seis
              imagens
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> Espaço em nosso
              Banner
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> 10% do valor
              convertido em publicidade
            </p>

            <button>Quero Doar</button>
          </div>

          <div className={`${styles.donationBox} ${styles.second}`}>
            <span>
              Benefícios II
              <FaStar className={styles.star} />
              <FaStar className={styles.star} />
            </span>
            <strong>
              R$ 1.000,00 <FaPlus />
            </strong>

            <p>
              <FaCheckDouble className={styles.checked} /> Pacote com seis
              imagens
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> Espaço em nosso
              Banner
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> 6% do valor
              convertido em publicidade
            </p>

            <button>Quero Doar</button>
          </div>

          <div className={`${styles.donationBox} ${styles.third}`}>
            <span>
              Benefícios I
              <FaStar className={styles.star} />
            </span>
            <strong>
              R$ 500,00 <FaPlus />
            </strong>

            <p>
              <FaCheckDouble className={styles.checked} /> Espaço em nosso
              Banner
            </p>
            <p>
              <FaCheckDouble className={styles.checked} /> 3% do valor
              convertido em publicidade
            </p>

            <button>Quero Doar</button>
          </div>
        </div>
      </section>

      <section className={styles.teamSection}>
        <div className={`box ${styles.team}`}>
          <span>Acreditamos na construção uns dos outros e por isso</span>
          <h2>trabalhamos com alguns parceiros incríveis</h2>
          <p>
            Conheça nossos parceiros e contate-os caso precise de seus serviços.
          </p>

          <div className="team">
            <Swiper
              modules={[A11y, Autoplay, Navigation]}
              spaceBetween={40}
              slidesPerView={2}
              autoplay={{
                delay: 5000,
              }}
              navigation
              loop={true}
              speed={1800}
              onSwiper={(swiper) => console.log(swiper)}
              onSlideChange={() => console.log("slide change")}
              className={styles.swiper}
            >
              <SwiperSlide>
                <div className={styles.person}>
                  <img src="/images/person01.jpg" alt="" />
                  <div className={styles.details}>
                    <p>
                      `&rdquo;`One disadvantage of Lorum Ipsum is that in Latin
                      certain letters appear more frequently than
                      others.`&rdquo;`
                    </p>
                    <span>Jonata Santos</span>
                    <strong>Desenvolvedor Web, Programador</strong>
                  </div>
                </div>
              </SwiperSlide>

              <SwiperSlide>
                <div className={styles.person}>
                  <img src="/images/person02.png" alt="" />
                  <div className={styles.details}>
                    <p>
                      `&rdquo;`26 anos de idade Atleta Bicampeã internacional,
                      Campeã paulista na categoria 59kg 10 lutas 8
                      vitórias.`&rdquo;`
                    </p>
                    <span>Prof: Thaty Azevedo</span>
                    <strong>Atleta e Professora de Muay Thai</strong>
                  </div>
                </div>
              </SwiperSlide>

              <SwiperSlide>
                <div className={styles.person}>
                  <img src="/images/person03.png" alt="" />
                  <div className={styles.details}>
                    <p>
                      `&rdquo;`Formado no Curso Superior de Tecnologia em Análise e Desenvolvimento de Sistemas
                      com 29 certificações complementares. `&rdquo;`
                    </p>
                    <span>Nicolas Max</span>
                    <strong>Analista de Sistemas</strong>
                  </div>
                </div>
              </SwiperSlide>

              <SwiperSlide>
                <div className={styles.person}>
                  <img src="/images/person01.jpg" alt="" />
                  <div className={styles.details}>
                    <p>
                      `&rdquo;`One disadvantage of Lorum Ipsum is that in Latin
                      certain letters appear more frequently than
                      others.`&rdquo;`
                    </p>
                    <span>Jonata Santos</span>
                    <strong>Desenvolvedor Web, Programador</strong>
                  </div>
                </div>
              </SwiperSlide>
            </Swiper>
          </div>

          <div className={styles.shapeQuestions}>
            <svg
              data-name="Layer 1"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 1200 120"
              preserveAspectRatio="none"
            >
              <path
                d="M1200 120L0 16.48 0 0 1200 0 1200 120z"
                className={styles.shapeFill}
              ></path>
            </svg>
          </div>
        </div>
      </section>

      <section className={styles.questionsSection}>
        <div className="box">
          <div className={styles.questions}>
            <div className={styles.question}>
              <h4>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                  <line x1="12" y1="17" x2="12.01" y2="17"></line>
                </svg>
                Quem pode fazer parte do projeto ?
              </h4>
              <p>
                Crianças que se encontram em pobreza, que não tem oportunidade
                de praticar um esporte e mulheres sem condições financeiras que
                sofreram violência domestica.
              </p>
            </div>

            <div className={styles.question}>
              <h4>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                  <line x1="12" y1="17" x2="12.01" y2="17"></line>
                </svg>
                Quais áreas o Muay Thai pode trazer mudança na vida dos alunos
                sociais ?
              </h4>
              <p>
                Entre todos os benefícios que o Muay Thai traz, jugamos
                importante o fato dele trazer desenvolvimento cognitivo,
                concentração, equilibrio físico e mental.
              </p>
            </div>

            <div className={styles.question}>
              <h4>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                  <line x1="12" y1="17" x2="12.01" y2="17"></line>
                </svg>
                Por que esse projeto é tão importante ?
              </h4>
              <p>
                O projeto Configurando Destinos veio para transformar vidas com
                esporte, trazendo através do Muay Thai disciplina, foco,
                determinação e respeito. Esses princípios podem ser levado para
                fora dos tatames construindo uma sociedade melhor.
              </p>
            </div>

            <div className={styles.question}>
              <h4>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <circle cx="12" cy="12" r="10"></circle>
                  <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                  <line x1="12" y1="17" x2="12.01" y2="17"></line>
                </svg>
                Até que idade posso participar do projeto ?
              </h4>
              <p>
                Meninos a partir dos 5 até os 12 anos de idade e meninas a
                partir dos 5 anos de idade e mulheres de todas as idades.
              </p>
            </div>
          </div>

          <div className="contact"></div>
        </div>
      </section>

      <section className={styles.contactSection}>
        <div className="box">
          <div className={styles.contact}>
            <h2>Tem alguma dúvida? entre em contato conosco!</h2>
            <p>Não hesite em nos contatar, sera sempre um prazer atende-lo!!</p>
            <button>Contate nos</button>
          </div>
        </div>

        <div className={styles.shapeDivider}>
          <svg
            data-name="Layer 1"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
          >
            <path
              d="M1200 120L0 16.48 0 0 1200 0 1200 120z"
              className={styles.shapeFill}
            ></path>
          </svg>
        </div>
      </section>
    </div>
  );
};

export default Home;

export const useEventListener = (
  target: EventTarget | undefined,
  event: string,
  listener: EventListenerOrEventListenerObject,
  trigger = true
): void => {
  useEffect(() => {
    const t = target || window;
    t.addEventListener(event, listener);
    trigger && t.dispatchEvent(new Event(event));
    return () => t.removeEventListener(event, listener);
  });
};
